//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Varijanta
    {
        public int ID { get; set; }
        public string Oznaka_motora { get; set; }
        public Nullable<int> Mjenjač { get; set; }
        public Nullable<int> Karoserija { get; set; }
        public int ID_modela { get; set; }
    
        public virtual Model Model { get; set; }
    }
}
