//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vlasnistvo
    {
        public int ID_vlasnik { get; set; }
        public int ID_vozilo { get; set; }
        public System.DateTime Pocetak_vlasnistva { get; set; }
        public Nullable<System.DateTime> Kraj_vlasnistva { get; set; }
    
        public virtual Vlasnik Vlasnik { get; set; }
        public virtual Vozilo Vozilo { get; set; }
    }
}
