//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vozilo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vozilo()
        {
            this.Servis = new HashSet<Servis>();
            this.Vlasnistvo = new HashSet<Vlasnistvo>();
        }
    
        public int ID { get; set; }
        public string VIN { get; set; }
        public string Reg_oznaka { get; set; }
        public Nullable<System.DateTime> Reg_do { get; set; }
        public Nullable<System.DateTime> God_proizvodnje { get; set; }
        public int ID_varijante { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servis> Servis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vlasnistvo> Vlasnistvo { get; set; }
    }
}
