//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS
{
    using System;
    using System.Collections.Generic;
    
    public partial class voziloView
    {
        public int ID { get; set; }
        public string VIN { get; set; }
        public string Vozilo { get; set; }
        public string Registarska_oznaka { get; set; }
        public Nullable<System.DateTime> Registriran_do { get; set; }
        public Nullable<System.DateTime> Godina_proizvodnje { get; set; }
    }
}
